import type { BlogNotificationPreferences, NotificationsPage } from "./notifications";
import { mockPendingFollowRequests } from "./follow-requests";

/** Demo/mock mode — lets the bell + page render and interact without a backend. */
export const USE_MOCKS = process.env.NEXT_PUBLIC_USE_MOCKS === "1";

const BASE = {
  postId: null,
  postSlug: null,
  postTitle: null,
  postAuthorUsername: null,
  seriesId: null,
  seriesSlug: null,
  seriesTitle: null,
  collectionId: null,
  collectionName: null,
} as const;

export function mockNotificationsPage(): NotificationsPage {
  const requests = mockPendingFollowRequests().map((r, i) => ({
    ...BASE,
    id: 700 + i,
    type: "FOLLOW_REQUEST" as const,
    actorId: null,
    actorUsername: r.handle,
    actorAvatarUrl: null,
    actorProfileUrl: "remoteId" in r.origin ? `https://${r.handle.split("@")[1]}/@${r.handle.split("@")[0]}` : null,
    actorRemoteId: "remoteId" in r.origin ? r.origin.remoteId : null,
    read: false,
    createdAt: r.requestedAt ?? new Date().toISOString(),
  }));
  return {
    items: [
      ...requests,
      {
        ...BASE,
        id: 21,
        type: "NOTE_LIKE",
        actorId: null,
        actorUsername: "alice@mastodon.social",
        actorAvatarUrl: null,
        actorProfileUrl: "https://mastodon.social/@alice",
        noteId: 2,
        noteExcerpt: "블로그 글을 인용해 봤어요.",
        count: 4,
        actors: [
          { id: null, username: "alice@mastodon.social", avatarUrl: null, profileUrl: "https://mastodon.social/@alice" },
          { id: 15, username: "yuna", avatarUrl: "https://i.pravatar.cc/120?img=20", profileUrl: null },
          { id: 16, username: "daniel", avatarUrl: null, profileUrl: null },
        ],
        read: false,
        createdAt: "2026-06-07T11:40:00Z",
      },
      {
        ...BASE,
        id: 20,
        type: "NOTE_REPLY",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        noteId: 2,
        noteExcerpt: "블로그 글을 인용해 봤어요.",
        sourceNoteId: 3,
        sourceExcerpt: "오늘 쓴 글의 씨앗: 단축 링크가 사라지면 글도 같이 끊긴다",
        count: 1,
        actors: [{ id: 15, username: "yuna", avatarUrl: "https://i.pravatar.cc/120?img=20", profileUrl: null }],
        read: false,
        createdAt: "2026-06-07T11:30:00Z",
      },
      {
        ...BASE,
        id: 21,
        type: "NOTE_MENTION",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        noteId: 5,
        noteExcerpt: "산책하다 찍은 것들. 길이 다 다르게 생겼다.",
        count: 1,
        actors: [{ id: 15, username: "yuna", avatarUrl: "https://i.pravatar.cc/120?img=20", profileUrl: null }],
        read: false,
        createdAt: "2026-06-07T11:20:00Z",
      },
      {
        ...BASE,
        id: 24,
        type: "NOTE_POST",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        noteId: 6,
        noteExcerpt: "오늘은 짧게. 내일 길게 쓸 것.",
        count: 1,
        actors: [{ id: 15, username: "yuna", avatarUrl: "https://i.pravatar.cc/120?img=20", profileUrl: null }],
        read: false,
        createdAt: "2026-06-07T11:15:00Z",
      },
      {
        ...BASE,
        id: 25,
        type: "NOTE_EDIT",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        noteId: 5,
        noteExcerpt: "산책하다 찍은 것들. 길이 다 다르게 생겼다.",
        count: 1,
        actors: [{ id: 15, username: "yuna", avatarUrl: "https://i.pravatar.cc/120?img=20", profileUrl: null }],
        read: true,
        createdAt: "2026-06-07T11:10:00Z",
      },
      {
        ...BASE,
        id: 19,
        type: "REMOTE_FOLLOW",
        actorId: null,
        actorUsername: "bob@fosstodon.org",
        actorAvatarUrl: null,
        actorProfileUrl: "https://fosstodon.org/@bob",
        count: 1,
        actors: [{ id: null, username: "bob@fosstodon.org", avatarUrl: null, profileUrl: "https://fosstodon.org/@bob" }],
        read: true,
        createdAt: "2026-06-07T11:25:00Z",
      },
      {
        ...BASE,
        id: 9,
        type: "CONNECTED",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        collectionId: 3,
        collectionName: "타입 시스템 깊게 읽기",
        read: false,
        createdAt: "2026-06-07T11:20:00Z",
      },
      {
        ...BASE,
        id: 8,
        type: "PATH_GREW",
        actorId: 16,
        actorUsername: "daniel",
        actorAvatarUrl: null,
        postId: 21,
        postSlug: "structural-typing",
        postTitle: "구조적 타이핑으로 다시 보는 인터페이스",
        collectionId: 3,
        collectionName: "타입 시스템 깊게 읽기",
        read: false,
        createdAt: "2026-06-07T11:12:00Z",
      },
      {
        ...BASE,
        id: 7,
        type: "MENTION",
        actorId: 12,
        actorUsername: "kazuki",
        actorAvatarUrl: null,
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        postAuthorUsername: "minji",
        read: false,
        createdAt: "2026-06-07T11:05:00Z",
      },
      {
        ...BASE,
        id: 6,
        type: "NEW_POST",
        actorId: 14,
        actorUsername: "sora",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=12",
        postId: 9,
        postSlug: "rust-ownership",
        postTitle: "러스트 소유권을 다시 정리하며",
        read: false,
        createdAt: "2026-06-07T11:00:00Z",
      },
      {
        ...BASE,
        id: 5,
        type: "REPLY",
        actorId: 12,
        actorUsername: "kazuki",
        actorAvatarUrl: null,
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        postAuthorUsername: "minji",
        read: false,
        createdAt: "2026-06-07T10:45:00Z",
      },
      {
        ...BASE,
        id: 4,
        type: "SERIES_SUBSCRIBE",
        actorId: 13,
        actorUsername: "haruki",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=8",
        seriesId: 2,
        seriesSlug: "frontend-deep-dive",
        seriesTitle: "프런트엔드 딥다이브",
        read: false,
        createdAt: "2026-06-07T10:35:00Z",
      },
      {
        ...BASE,
        id: 3,
        type: "LIKE",
        actorId: 11,
        actorUsername: "minji",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=5",
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        count: 3,
        actors: [
          { id: 11, username: "minji", avatarUrl: "https://i.pravatar.cc/120?img=5", profileUrl: null },
          { id: 12, username: "kazuki", avatarUrl: null, profileUrl: null },
        ],
        read: false,
        createdAt: "2026-06-07T10:30:00Z",
      },
      {
        ...BASE,
        id: 31,
        type: "HIGHLIGHT",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        highlightId: 7,
        count: 2,
        read: false,
        createdAt: "2026-06-07T10:20:00Z",
      },
      {
        ...BASE,
        id: 32,
        type: "COMMENT_LIKE",
        actorId: 13,
        actorUsername: "haruki",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=8",
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        commentId: 3,
        count: 1,
        read: true,
        createdAt: "2026-06-07T10:10:00Z",
      },
      {
        ...BASE,
        id: 33,
        type: "POST_QUOTE",
        actorId: 15,
        actorUsername: "yuna",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=20",
        noteId: 6,
        noteExcerpt: "제네릭은 타입에 이름을 붙이는 일이라는 말이 오래 남는다.",
        count: 1,
        read: true,
        createdAt: "2026-06-07T10:05:00Z",
      },
      {
        ...BASE,
        id: 34,
        type: "NOTE_EMBED",
        actorId: 12,
        actorUsername: "kazuki",
        actorAvatarUrl: null,
        postId: 8,
        postSlug: "weekly-notes",
        postTitle: "이번 주 노트 모음",
        postAuthorUsername: "kazuki",
        count: 1,
        read: true,
        createdAt: "2026-06-07T10:00:00Z",
      },
      {
        ...BASE,
        id: 2,
        type: "COMMENT",
        actorId: 12,
        actorUsername: "kazuki",
        actorAvatarUrl: null,
        postId: 5,
        postSlug: "typescript-generics",
        postTitle: "타입스크립트 제네릭이 어려운 이유",
        commentId: 3,
        read: false,
        createdAt: "2026-06-07T09:15:00Z",
      },
      {
        ...BASE,
        id: 1,
        type: "FOLLOW",
        actorId: 13,
        actorUsername: "haruki",
        actorAvatarUrl: "https://i.pravatar.cc/120?img=8",
        read: true,
        createdAt: "2026-06-06T14:20:00Z",
      },
    ],
    nextCursor: null,
    hasMore: false,
  };
}

export function mockUnreadCount(): { count: number } {
  return { count: 6 };
}

/** Demo preferences with a couple of types muted, so the off-state is visible without a backend. */
export function mockBlogNotificationPreferences(): BlogNotificationPreferences {
  return {
    LIKE: true,
    COMMENT: true,
    FOLLOW: false,
    SERIES_SUBSCRIBE: true,
    REPLY: true,
    NEW_POST: false,
    MENTION: true,
    CONNECTED: true,
    PATH_GREW: true,
    NOTE_LIKE: true,
    NOTE_REPOST: true,
    NOTE_REPLY: true,
    NOTE_QUOTE: true,
    NOTE_MENTION: true,
    NOTE_POLL: true,
    NOTE_POST: true,
    NOTE_EDIT: true,
    REMOTE_FOLLOW: true,
    FOLLOW_REQUEST: true,
    POST_QUOTE: true,
    NOTE_EMBED: true,
    COMMENT_LIKE: true,
    HIGHLIGHT: true,
  };
}
